-- A college needs to develop a system that tracks the Open Elective Subjects of their students. During the start of
-- the year a lot of students change their subjects and college wants to preserve that entire timeline of the data.
-- For example, Mohit had selected “Eco philosophy” as his Open Elective subject but later he wished to switch to
-- “Basics of Accounting” in this scenario the college wants the visibility of Mohit’s previous choice as well instead
-- of just the active one:
-- There is one table that holds the record of this change, and it is called SubjectAllotments
